### ISSUE TITLE
Calendar widget not responding when tapped on date

### ISSUE THREAD

**Issue by dinurymomshad** [KalleHallden/exer_log#33] opened 2022-08-08 08:09 UTC
**Steps to reproduce:**
1. Login
2. Add a new work out
3. Pop back to Calendar page
4. Click on current date
5. Observe nothing happens

_Current_: Nothing happens
_Expected_: I should be able to see workout for that day

Video:
https://user-images.githubusercontent.com/26508767/183371431-7f9350e4-0758-40ef-ae41-5e3f5bf6522c.mp4

**Comment by dinurymomshad** [comment] 2022-08-08 08:13
@KalleHallden 👀

**Comment by dinurymomshad** [comment] 2022-08-08 08:17
@KalleHallden I haven't tested this branch but is it possible that this branch (https://github.com/KalleHallden/exer_log/tree/calendar-page) wasn't merged and the feature is working fine there?

**Comment by ckelwin** [comment] 2022-08-08 15:18
@dinurymomshad 
The `calendar-page` branch contains 1 line of code change that does not affect functionality.

I believe the issue is that you clicked on the `back` button (left arrow at the top right). You should have clicked on the checkmark icon on the top right.

![image](https://user-images.githubusercontent.com/5429312/183451794-85710e53-a378-47ac-b863-2cfd254dbef8.png)

@KalleHallden For this use case that @dinurymomshad shared, we may need a 'confirmation dialog' when `back` button is pressed. Something like "Your workout is not saved. Are you sure?"

**Comment by dinurymomshad** [comment] 2022-08-08 16:32
Hah, was wondering what that button was for. Thanks @ckelwin

**Comment by ckelwin** [comment] 2022-08-08 18:11
@dinurymomshad  Safe to close this issue then?

**Closed** 2022-08-08 18:23 UTC
